server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/api/wallets/**
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/api/cards/**
        - id: kyc-service
          uri: lb://kyc-service
          predicates:
            - Path=/api/kyc/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/